#
# SPDX-License-Identifier: GPL-2.0-only
#
# @author Arthur Lapz <rlapz@gnuweeb.org>
# @license GPL-2.0-only
#
# Copyright (C) 2023  Arthur Lapz
#

DEP_DIRS	+= $(BASE_DEP_DIR)/src/ext/charm
OBJ_CC		+= $(BASE_DIR)/src/ext/charm/charm.o
